name: framework
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: 1.1.0 #屏幕适配
  fluttertoast: 3.1.3 #toast
  qr_flutter: 3.2.0 #生成二维码
  carousel_slider: 1.4.1 #轮播图
  cached_network_image: 2.0.0 #网络图片加载
  flutter_spinkit: 4.1.2
  flutter_easyrefresh: 2.1.0 #上下拉刷线 
  shared_preferences: 0.5.6+3 #本地存储
  json_annotation: 2.3.0 #序/反序列化
  analyzer: 0.36.0 #序/反序列化 
  common_utils: 1.1.3 #常用工具
  permission_handler: #系统权限
  image_gallery_saver: #保存图片 
  barcode_scan: #二维码扫描
  transparent_image :  #展位图片
  event_bus : #广播消息
  provider:  #状态管理
  dio: 3.0.9 #网络请求 
  flutter_keyboard_visibility: #键盘
  keyboard_actions: #键盘
  device_info: #设备信息
  decimal: 0.3.5 #精度处理  
  flutter_staggered_grid_view: #瀑布流
  date_format: ^1.0.6 #日期/时间格式化 
  flutterautotext: #自适应缩放字体大小
    git: https://github.com/LiuC520/flutterautotext.git
  webview_flutter:
    path: /Users/zick/zwork/tools/flutter_plugins/packages/webview_flutter
  bubble_tab_indicator: 0.1.4 
  # flutter_localizations: #国际化 
    
  #XM
  # xm_nav_router:
  #   git: git://github.com/smallsevenk/xm_nav_router.git

  path_provider: ^1.5.1 
  flutter_downloader:


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    #comm
    - res/imgs/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: XMIcon
      fonts:
        - asset: res/fonts/XMIcon.ttf
    - family: iconfont
      fonts: 
        - asset: res/fonts/iconfont.ttf 
    - family: icomoon
      fonts: 
        - asset: res/fonts/icomoon.ttf
       
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
